In [1]:
import torch
from model import Maxout, GeneratorZero, DiscriminatorZero
from data import MNISTTrainDataLoader

In [2]:
## Maxout test
input_tensor = torch.randn(5)
input_tensor
maxout = Maxout(3, 5, 5)
maxout(input_tensor)

tensor([[ 1.7576, -0.5966,  0.1197,  0.8276,  0.4078],
        [ 0.1855,  1.3380, -0.1030,  0.6960, -0.4888],
        [ 0.0442, -0.1757,  0.0903,  0.3157,  1.8142]], grad_fn=<CatBackward0>)


tensor([1.7576, 1.3380, 0.1197, 0.8276, 1.8142], grad_fn=<MaxBackward0>)

In [3]:
## Generator test
input_noise = torch.randn(64 * 64)
generator = GeneratorZero() #13.4s to load
generated = generator(input_noise) #4.5s to inference

In [4]:
## Discriminator test
discriminator = DiscriminatorZero()

In [5]:
discriminator(generated)

tensor([[-0.3096, -0.1617,  0.0407,  ...,  0.1730, -0.0835, -0.0271],
        [-0.0959, -0.2139, -0.2853,  ...,  0.1883, -0.0151,  0.2537],
        [-0.4171,  0.1412, -0.2772,  ...,  0.2737,  0.2526, -0.2261],
        [ 0.0037, -0.1928,  0.3753,  ..., -0.0366,  0.0331, -0.0957],
        [-0.1233,  0.0349,  0.0480,  ..., -0.1634,  0.0293,  0.1158]],
       grad_fn=<CatBackward0>)
tensor([[ 0.0081,  0.0898,  0.0488,  ..., -0.0031,  0.0403,  0.1434],
        [-0.0341,  0.0195, -0.1025,  ...,  0.1069, -0.0215,  0.0022],
        [-0.0137, -0.1366, -0.1502,  ..., -0.0563,  0.0581, -0.0432],
        [ 0.1399, -0.0651,  0.0372,  ...,  0.0513,  0.0556,  0.1894],
        [ 0.0439,  0.0461,  0.0631,  ...,  0.0226, -0.0095, -0.0130]],
       grad_fn=<CatBackward0>)
tensor([[-0.1813],
        [ 0.0833],
        [-0.0015],
        [ 0.1843],
        [ 0.0160]], grad_fn=<CatBackward0>)


tensor([0.1843], grad_fn=<MaxBackward0>)